{
    "inputs": {
        "dependency": "tensorflow",
        "outfile": "/home/vanessa/Desktop/Code/caliper-analysis/.caliper/pypi-tensorflow-1.13.0rc0-python-cp27.json",
        "dockerfile": "FROM python:2.7\nADD . /tmp/repo\nWORKDIR /tmp/repo\nENV LANG C.UTF-8\nENV SHELL /bin/bash\nRUN apt-get update && apt-get install -y wget ca-certificates gnupg2 git\nRUN /bin/bash -c \"wget https://files.pythonhosted.org/packages/a9/31/d6fa0806c1a9804d545b360353d1eabaa15374498916722ecb204b3491ed/tensorflow-1.13.0rc0-cp27-cp27mu-manylinux1_x86_64.whl && pip install tensorflow-1.13.0rc0-cp27-cp27mu-manylinux1_x86_64.whl\"\n",
        "force": false,
        "exists": true,
        "name": "pypi-tensorflow-1.13.0rc0-python-cp27",
        "tests": "tensorflow_v0.11/5_MultiGPU/multigpu_basics.py\ntensorflow_v0.11/1_Introduction/basic_operations.py\ntensorflow_v0.11/1_Introduction/helloworld.py\ntensorflow_v0.11/4_Utils/tensorboard_advanced.py\ntensorflow_v0.11/4_Utils/tensorboard_basic.py\ntensorflow_v0.11/2_BasicModels/logistic_regression.py\ntensorflow_v0.11/2_BasicModels/linear_regression.py\ntensorflow_v0.11/2_BasicModels/nearest_neighbor.py\ntensorflow_v0.11/3_NeuralNetworks/bidirectional_rnn.py\ntensorflow_v0.11/3_NeuralNetworks/autoencoder.py\ntensorflow_v0.11/3_NeuralNetworks/recurrent_network.py\ntensorflow_v0.11/3_NeuralNetworks/dynamic_rnn.py\ntensorflow_v0.11/3_NeuralNetworks/multilayer_perceptron.py\ntensorflow_v0.11/3_NeuralNetworks/convolutional_network.py\ntensorflow_v1/1_Introduction/basic_eager_api.py\ntensorflow_v1/1_Introduction/basic_operations.py\ntensorflow_v1/1_Introduction/helloworld.py\ntensorflow_v1/4_Utils/tensorboard_advanced.py\ntensorflow_v1/4_Utils/tensorboard_basic.py\ntensorflow_v1/5_DataManagement/build_an_image_dataset.py\ntensorflow_v1/5_DataManagement/tensorflow_dataset_api.py\ntensorflow_v1/2_BasicModels/random_forest.py\ntensorflow_v1/2_BasicModels/gradient_boosted_decision_tree.py\ntensorflow_v1/2_BasicModels/logistic_regression.py\ntensorflow_v1/2_BasicModels/word2vec.py\ntensorflow_v1/2_BasicModels/linear_regression.py\ntensorflow_v1/2_BasicModels/logistic_regression_eager_api.py\ntensorflow_v1/2_BasicModels/nearest_neighbor.py\ntensorflow_v1/2_BasicModels/linear_regression_eager_api.py\ntensorflow_v1/2_BasicModels/kmeans.py\ntensorflow_v1/6_MultiGPU/multigpu_basics.py\ntensorflow_v1/6_MultiGPU/multigpu_cnn.py\ntensorflow_v1/3_NeuralNetworks/variational_autoencoder.py\ntensorflow_v1/3_NeuralNetworks/neural_network_eager_api.py\ntensorflow_v1/3_NeuralNetworks/neural_network.py\ntensorflow_v1/3_NeuralNetworks/bidirectional_rnn.py\ntensorflow_v1/3_NeuralNetworks/convolutional_network_raw.py\ntensorflow_v1/3_NeuralNetworks/autoencoder.py\ntensorflow_v1/3_NeuralNetworks/gan.py\ntensorflow_v1/3_NeuralNetworks/recurrent_network.py\ntensorflow_v1/3_NeuralNetworks/neural_network_raw.py\ntensorflow_v1/3_NeuralNetworks/multilayer_perceptron.py\ntensorflow_v1/3_NeuralNetworks/convolutional_network.py",
        "cleanup": true,
        "outdir": "/home/vanessa/Desktop/Code/caliper-analysis"
    },
    "tests": {
        "build": {
            "retval": 0
        },
        "tensorflow_v0.11/5_MultiGPU/multigpu_basics.py": {
            "error": [
                "2021-01-04 12:49:44.209186: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA\n",
                "2021-01-04 12:49:44.212803: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 1999965000 Hz\n",
                "2021-01-04 12:49:44.213089: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55a62f93a650 executing computations on platform Host. Devices:\n",
                "2021-01-04 12:49:44.213110: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>\n",
                "2021-01-04 12:49:44.213383: I tensorflow/core/common_runtime/direct_session.cc:317] Device mapping:\n",
                "/job:localhost/replica:0/task:0/device:XLA_CPU:0 -> device: XLA_CPU device\n",
                "\n",
                "2021-01-04 12:49:44.214761: I tensorflow/core/common_runtime/placer.cc:1059] MatMul: (MatMul)/job:localhost/replica:0/task:0/device:CPU:0\n",
                "2021-01-04 12:49:44.214786: I tensorflow/core/common_runtime/placer.cc:1059] MatMul_1: (MatMul)/job:localhost/replica:0/task:0/device:CPU:0\n",
                "2021-01-04 12:49:44.214794: I tensorflow/core/common_runtime/placer.cc:1059] AddN: (AddN)/job:localhost/replica:0/task:0/device:CPU:0\n",
                "2021-01-04 12:49:44.214801: I tensorflow/core/common_runtime/placer.cc:1059] Placeholder: (Placeholder)/job:localhost/replica:0/task:0/device:CPU:0\n",
                "2021-01-04 12:49:44.214807: I tensorflow/core/common_runtime/placer.cc:1059] Placeholder_1: (Placeholder)/job:localhost/replica:0/task:0/device:CPU:0\n",
                "2021-01-04 12:49:44.248947: I tensorflow/core/common_runtime/direct_session.cc:317] Device mapping:\n",
                "/job:localhost/replica:0/task:0/device:XLA_CPU:0 -> device: XLA_CPU device\n",
                "\n",
                "2021-01-04 12:49:44.249700: I tensorflow/core/common_runtime/placer.cc:1059] MatMul: (MatMul)/job:localhost/replica:0/task:0/device:CPU:0\n",
                "2021-01-04 12:49:44.249724: I tensorflow/core/common_runtime/placer.cc:1059] MatMul_1: (MatMul)/job:localhost/replica:0/task:0/device:CPU:0\n",
                "2021-01-04 12:49:44.249731: I tensorflow/core/common_runtime/placer.cc:1059] AddN: (AddN)/job:localhost/replica:0/task:0/device:CPU:0\n",
                "2021-01-04 12:49:44.249736: I tensorflow/core/common_runtime/placer.cc:1059] MatMul_2: (MatMul)/job:localhost/replica:0/task:0/device:CPU:0\n",
                "2021-01-04 12:49:44.249741: I tensorflow/core/common_runtime/placer.cc:1059] MatMul_3: (MatMul)/job:localhost/replica:0/task:0/device:CPU:0\n",
                "2021-01-04 12:49:44.249747: I tensorflow/core/common_runtime/placer.cc:1059] AddN_1: (AddN)/job:localhost/replica:0/task:0/device:CPU:0\n",
                "2021-01-04 12:49:44.249752: I tensorflow/core/common_runtime/placer.cc:1059] Placeholder: (Placeholder)/job:localhost/replica:0/task:0/device:CPU:0\n",
                "2021-01-04 12:49:44.249757: I tensorflow/core/common_runtime/placer.cc:1059] Placeholder_1: (Placeholder)/job:localhost/replica:0/task:0/device:CPU:0\n",
                "2021-01-04 12:49:44.249762: I tensorflow/core/common_runtime/placer.cc:1059] Placeholder_2: (Placeholder)/job:localhost/replica:0/task:0/device:CPU:0\n",
                "2021-01-04 12:49:44.249768: I tensorflow/core/common_runtime/placer.cc:1059] Placeholder_3: (Placeholder)/job:localhost/replica:0/task:0/device:CPU:0\n"
            ],
            "output": [
                "Device mapping:\n",
                "/job:localhost/replica:0/task:0/device:XLA_CPU:0 -> device: XLA_CPU device\n",
                "MatMul: (MatMul): /job:localhost/replica:0/task:0/device:CPU:0\n",
                "MatMul_1: (MatMul): /job:localhost/replica:0/task:0/device:CPU:0\n",
                "AddN: (AddN): /job:localhost/replica:0/task:0/device:CPU:0\n",
                "Placeholder: (Placeholder): /job:localhost/replica:0/task:0/device:CPU:0\n",
                "Placeholder_1: (Placeholder): /job:localhost/replica:0/task:0/device:CPU:0\n",
                "Device mapping:\n",
                "/job:localhost/replica:0/task:0/device:XLA_CPU:0 -> device: XLA_CPU device\n",
                "MatMul: (MatMul): /job:localhost/replica:0/task:0/device:CPU:0\n",
                "MatMul_1: (MatMul): /job:localhost/replica:0/task:0/device:CPU:0\n",
                "AddN: (AddN): /job:localhost/replica:0/task:0/device:CPU:0\n",
                "MatMul_2: (MatMul): /job:localhost/replica:0/task:0/device:CPU:0\n",
                "MatMul_3: (MatMul): /job:localhost/replica:0/task:0/device:CPU:0\n",
                "AddN_1: (AddN): /job:localhost/replica:0/task:0/device:CPU:0\n",
                "Placeholder: (Placeholder): /job:localhost/replica:0/task:0/device:CPU:0\n",
                "Placeholder_1: (Placeholder): /job:localhost/replica:0/task:0/device:CPU:0\n",
                "Placeholder_2: (Placeholder): /job:localhost/replica:0/task:0/device:CPU:0\n",
                "Placeholder_3: (Placeholder): /job:localhost/replica:0/task:0/device:CPU:0\n",
                "Single CPU computation time: 0:00:00.036665\n",
                "Multi CPU computation time: 0:00:00.030811\n"
            ],
            "retval": 0,
            "seconds": 1.79
        },
        "tensorflow_v0.11/1_Introduction/basic_operations.py": {
            "error": [
                "2021-01-04 12:49:46.048372: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA\n",
                "2021-01-04 12:49:46.052375: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 1999965000 Hz\n",
                "2021-01-04 12:49:46.052765: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x559d3e062f00 executing computations on platform Host. Devices:\n",
                "2021-01-04 12:49:46.052791: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>\n"
            ],
            "output": [
                "a=2, b=3\n",
                "Addition with constants: 5\n",
                "Multiplication with constants: 6\n",
                "Addition with variables: 5\n",
                "Multiplication with variables: 6\n",
                "[[12.]]\n"
            ],
            "retval": 0,
            "seconds": 1.69
        },
        "tensorflow_v0.11/1_Introduction/helloworld.py": {
            "error": [
                "2021-01-04 12:49:47.780939: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA\n",
                "2021-01-04 12:49:47.786126: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 1999965000 Hz\n",
                "2021-01-04 12:49:47.786480: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55a7bcfe7180 executing computations on platform Host. Devices:\n",
                "2021-01-04 12:49:47.786503: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>\n"
            ],
            "output": [
                "Hello, TensorFlow!\n"
            ],
            "retval": 0,
            "seconds": 1.83
        },
        "tensorflow_v0.11/4_Utils/tensorboard_advanced.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v0.11/4_Utils/tensorboard_advanced.py\", line 21, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/__init__.py\", line 21, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/input_data.py\", line 30, in <module>\n",
                "    from tensorflow.contrib.learn.python.learn.datasets.mnist import read_data_sets\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/__init__.py\", line 40, in <module>\n",
                "    from tensorflow.contrib import distribute\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/__init__.py\", line 33, in <module>\n",
                "    from tensorflow.contrib.distribute.python.tpu_strategy import TPUStrategy\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/tpu_strategy.py\", line 27, in <module>\n",
                "    from tensorflow.contrib.tpu.python.ops import tpu_ops\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/__init__.py\", line 73, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu.keras_support import tpu_model as keras_to_tpu_model\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py\", line 62, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu import tpu\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu.py\", line 24, in <module>\n",
                "    from tensorflow.contrib.compiler import xla\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/compiler/xla.py\", line 28, in <module>\n",
                "    from tensorflow.python.estimator import model_fn as model_fn_lib\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/python/estimator/__init__.py\", line 26, in <module>\n",
                "    from tensorflow_estimator.python import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1 import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1.estimator import experimental\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py\", line 31, in <module>\n",
                "    from tensorflow_estimator.python.estimator import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py\", line 33, in <module>\n",
                "    from tensorflow.python.eager import monitoring\n",
                "ImportError: cannot import name monitoring\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 1.93
        },
        "tensorflow_v0.11/4_Utils/tensorboard_basic.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v0.11/4_Utils/tensorboard_basic.py\", line 21, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/__init__.py\", line 21, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/input_data.py\", line 30, in <module>\n",
                "    from tensorflow.contrib.learn.python.learn.datasets.mnist import read_data_sets\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/__init__.py\", line 40, in <module>\n",
                "    from tensorflow.contrib import distribute\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/__init__.py\", line 33, in <module>\n",
                "    from tensorflow.contrib.distribute.python.tpu_strategy import TPUStrategy\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/tpu_strategy.py\", line 27, in <module>\n",
                "    from tensorflow.contrib.tpu.python.ops import tpu_ops\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/__init__.py\", line 73, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu.keras_support import tpu_model as keras_to_tpu_model\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py\", line 62, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu import tpu\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu.py\", line 24, in <module>\n",
                "    from tensorflow.contrib.compiler import xla\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/compiler/xla.py\", line 28, in <module>\n",
                "    from tensorflow.python.estimator import model_fn as model_fn_lib\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/python/estimator/__init__.py\", line 26, in <module>\n",
                "    from tensorflow_estimator.python import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1 import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1.estimator import experimental\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py\", line 31, in <module>\n",
                "    from tensorflow_estimator.python.estimator import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py\", line 33, in <module>\n",
                "    from tensorflow.python.eager import monitoring\n",
                "ImportError: cannot import name monitoring\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 1.71
        },
        "tensorflow_v0.11/2_BasicModels/logistic_regression.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v0.11/2_BasicModels/logistic_regression.py\", line 21, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/__init__.py\", line 21, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/input_data.py\", line 30, in <module>\n",
                "    from tensorflow.contrib.learn.python.learn.datasets.mnist import read_data_sets\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/__init__.py\", line 40, in <module>\n",
                "    from tensorflow.contrib import distribute\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/__init__.py\", line 33, in <module>\n",
                "    from tensorflow.contrib.distribute.python.tpu_strategy import TPUStrategy\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/tpu_strategy.py\", line 27, in <module>\n",
                "    from tensorflow.contrib.tpu.python.ops import tpu_ops\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/__init__.py\", line 73, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu.keras_support import tpu_model as keras_to_tpu_model\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py\", line 62, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu import tpu\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu.py\", line 24, in <module>\n",
                "    from tensorflow.contrib.compiler import xla\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/compiler/xla.py\", line 28, in <module>\n",
                "    from tensorflow.python.estimator import model_fn as model_fn_lib\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/python/estimator/__init__.py\", line 26, in <module>\n",
                "    from tensorflow_estimator.python import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1 import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1.estimator import experimental\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py\", line 31, in <module>\n",
                "    from tensorflow_estimator.python.estimator import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py\", line 33, in <module>\n",
                "    from tensorflow.python.eager import monitoring\n",
                "ImportError: cannot import name monitoring\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 1.93
        },
        "tensorflow_v0.11/2_BasicModels/linear_regression.py": {
            "error": [
                "WARNING:tensorflow:From /usr/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.\n",
                "Instructions for updating:\n",
                "Colocations handled automatically by placer.\n",
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v0.11/2_BasicModels/linear_regression.py\", line 81, in <module>\n",
                "    pred = tf.add(tf.mul(X, W), b)\n",
                "AttributeError: 'module' object has no attribute 'mul'\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 1.73
        },
        "tensorflow_v0.11/2_BasicModels/nearest_neighbor.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v0.11/2_BasicModels/nearest_neighbor.py\", line 23, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/__init__.py\", line 21, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/input_data.py\", line 30, in <module>\n",
                "    from tensorflow.contrib.learn.python.learn.datasets.mnist import read_data_sets\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/__init__.py\", line 40, in <module>\n",
                "    from tensorflow.contrib import distribute\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/__init__.py\", line 33, in <module>\n",
                "    from tensorflow.contrib.distribute.python.tpu_strategy import TPUStrategy\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/tpu_strategy.py\", line 27, in <module>\n",
                "    from tensorflow.contrib.tpu.python.ops import tpu_ops\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/__init__.py\", line 73, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu.keras_support import tpu_model as keras_to_tpu_model\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py\", line 62, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu import tpu\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu.py\", line 24, in <module>\n",
                "    from tensorflow.contrib.compiler import xla\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/compiler/xla.py\", line 28, in <module>\n",
                "    from tensorflow.python.estimator import model_fn as model_fn_lib\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/python/estimator/__init__.py\", line 26, in <module>\n",
                "    from tensorflow_estimator.python import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1 import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1.estimator import experimental\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py\", line 31, in <module>\n",
                "    from tensorflow_estimator.python.estimator import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py\", line 33, in <module>\n",
                "    from tensorflow.python.eager import monitoring\n",
                "ImportError: cannot import name monitoring\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 1.92
        },
        "tensorflow_v0.11/3_NeuralNetworks/bidirectional_rnn.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v0.11/3_NeuralNetworks/bidirectional_rnn.py\", line 24, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/__init__.py\", line 21, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/input_data.py\", line 30, in <module>\n",
                "    from tensorflow.contrib.learn.python.learn.datasets.mnist import read_data_sets\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/__init__.py\", line 40, in <module>\n",
                "    from tensorflow.contrib import distribute\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/__init__.py\", line 33, in <module>\n",
                "    from tensorflow.contrib.distribute.python.tpu_strategy import TPUStrategy\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/tpu_strategy.py\", line 27, in <module>\n",
                "    from tensorflow.contrib.tpu.python.ops import tpu_ops\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/__init__.py\", line 73, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu.keras_support import tpu_model as keras_to_tpu_model\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py\", line 62, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu import tpu\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu.py\", line 24, in <module>\n",
                "    from tensorflow.contrib.compiler import xla\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/compiler/xla.py\", line 28, in <module>\n",
                "    from tensorflow.python.estimator import model_fn as model_fn_lib\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/python/estimator/__init__.py\", line 26, in <module>\n",
                "    from tensorflow_estimator.python import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1 import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1.estimator import experimental\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py\", line 31, in <module>\n",
                "    from tensorflow_estimator.python.estimator import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py\", line 33, in <module>\n",
                "    from tensorflow.python.eager import monitoring\n",
                "ImportError: cannot import name monitoring\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 1.7
        },
        "tensorflow_v0.11/3_NeuralNetworks/autoencoder.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v0.11/3_NeuralNetworks/autoencoder.py\", line 25, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/__init__.py\", line 21, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/input_data.py\", line 30, in <module>\n",
                "    from tensorflow.contrib.learn.python.learn.datasets.mnist import read_data_sets\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/__init__.py\", line 40, in <module>\n",
                "    from tensorflow.contrib import distribute\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/__init__.py\", line 33, in <module>\n",
                "    from tensorflow.contrib.distribute.python.tpu_strategy import TPUStrategy\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/tpu_strategy.py\", line 27, in <module>\n",
                "    from tensorflow.contrib.tpu.python.ops import tpu_ops\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/__init__.py\", line 73, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu.keras_support import tpu_model as keras_to_tpu_model\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py\", line 62, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu import tpu\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu.py\", line 24, in <module>\n",
                "    from tensorflow.contrib.compiler import xla\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/compiler/xla.py\", line 28, in <module>\n",
                "    from tensorflow.python.estimator import model_fn as model_fn_lib\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/python/estimator/__init__.py\", line 26, in <module>\n",
                "    from tensorflow_estimator.python import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1 import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1.estimator import experimental\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py\", line 31, in <module>\n",
                "    from tensorflow_estimator.python.estimator import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py\", line 33, in <module>\n",
                "    from tensorflow.python.eager import monitoring\n",
                "ImportError: cannot import name monitoring\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 1.94
        },
        "tensorflow_v0.11/3_NeuralNetworks/recurrent_network.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v0.11/3_NeuralNetworks/recurrent_network.py\", line 22, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/__init__.py\", line 21, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/input_data.py\", line 30, in <module>\n",
                "    from tensorflow.contrib.learn.python.learn.datasets.mnist import read_data_sets\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/__init__.py\", line 40, in <module>\n",
                "    from tensorflow.contrib import distribute\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/__init__.py\", line 33, in <module>\n",
                "    from tensorflow.contrib.distribute.python.tpu_strategy import TPUStrategy\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/tpu_strategy.py\", line 27, in <module>\n",
                "    from tensorflow.contrib.tpu.python.ops import tpu_ops\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/__init__.py\", line 73, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu.keras_support import tpu_model as keras_to_tpu_model\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py\", line 62, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu import tpu\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu.py\", line 24, in <module>\n",
                "    from tensorflow.contrib.compiler import xla\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/compiler/xla.py\", line 28, in <module>\n",
                "    from tensorflow.python.estimator import model_fn as model_fn_lib\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/python/estimator/__init__.py\", line 26, in <module>\n",
                "    from tensorflow_estimator.python import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1 import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1.estimator import experimental\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py\", line 31, in <module>\n",
                "    from tensorflow_estimator.python.estimator import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py\", line 33, in <module>\n",
                "    from tensorflow.python.eager import monitoring\n",
                "ImportError: cannot import name monitoring\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 1.89
        },
        "tensorflow_v0.11/3_NeuralNetworks/dynamic_rnn.py": {
            "error": [
                "WARNING:tensorflow:From /usr/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.\n",
                "Instructions for updating:\n",
                "Colocations handled automatically by placer.\n",
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v0.11/3_NeuralNetworks/dynamic_rnn.py\", line 160, in <module>\n",
                "    pred = dynamicRNN(x, seqlen, weights, biases)\n",
                "  File \"tensorflow_v0.11/3_NeuralNetworks/dynamic_rnn.py\", line 128, in dynamicRNN\n",
                "    x = tf.split(0, seq_max_len, x)\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py\", line 1508, in split\n",
                "    axis=axis, num_split=num_or_size_splits, value=value, name=name)\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py\", line 8883, in split\n",
                "    \"Split\", split_dim=axis, value=value, num_split=num_split, name=name)\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py\", line 534, in _apply_op_helper\n",
                "    (prefix, dtypes.as_dtype(input_arg.type).name))\n",
                "TypeError: Input 'split_dim' of 'Split' Op has type float32 that does not match expected type of int32.\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 1.75
        },
        "tensorflow_v0.11/3_NeuralNetworks/multilayer_perceptron.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v0.11/3_NeuralNetworks/multilayer_perceptron.py\", line 13, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/__init__.py\", line 21, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/input_data.py\", line 30, in <module>\n",
                "    from tensorflow.contrib.learn.python.learn.datasets.mnist import read_data_sets\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/__init__.py\", line 40, in <module>\n",
                "    from tensorflow.contrib import distribute\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/__init__.py\", line 33, in <module>\n",
                "    from tensorflow.contrib.distribute.python.tpu_strategy import TPUStrategy\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/tpu_strategy.py\", line 27, in <module>\n",
                "    from tensorflow.contrib.tpu.python.ops import tpu_ops\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/__init__.py\", line 73, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu.keras_support import tpu_model as keras_to_tpu_model\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py\", line 62, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu import tpu\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu.py\", line 24, in <module>\n",
                "    from tensorflow.contrib.compiler import xla\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/compiler/xla.py\", line 28, in <module>\n",
                "    from tensorflow.python.estimator import model_fn as model_fn_lib\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/python/estimator/__init__.py\", line 26, in <module>\n",
                "    from tensorflow_estimator.python import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1 import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1.estimator import experimental\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py\", line 31, in <module>\n",
                "    from tensorflow_estimator.python.estimator import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py\", line 33, in <module>\n",
                "    from tensorflow.python.eager import monitoring\n",
                "ImportError: cannot import name monitoring\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 1.69
        },
        "tensorflow_v0.11/3_NeuralNetworks/convolutional_network.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v0.11/3_NeuralNetworks/convolutional_network.py\", line 21, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/__init__.py\", line 21, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/input_data.py\", line 30, in <module>\n",
                "    from tensorflow.contrib.learn.python.learn.datasets.mnist import read_data_sets\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/__init__.py\", line 40, in <module>\n",
                "    from tensorflow.contrib import distribute\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/__init__.py\", line 33, in <module>\n",
                "    from tensorflow.contrib.distribute.python.tpu_strategy import TPUStrategy\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/tpu_strategy.py\", line 27, in <module>\n",
                "    from tensorflow.contrib.tpu.python.ops import tpu_ops\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/__init__.py\", line 73, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu.keras_support import tpu_model as keras_to_tpu_model\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py\", line 62, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu import tpu\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu.py\", line 24, in <module>\n",
                "    from tensorflow.contrib.compiler import xla\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/compiler/xla.py\", line 28, in <module>\n",
                "    from tensorflow.python.estimator import model_fn as model_fn_lib\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/python/estimator/__init__.py\", line 26, in <module>\n",
                "    from tensorflow_estimator.python import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1 import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1.estimator import experimental\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py\", line 31, in <module>\n",
                "    from tensorflow_estimator.python.estimator import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py\", line 33, in <module>\n",
                "    from tensorflow.python.eager import monitoring\n",
                "ImportError: cannot import name monitoring\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 1.97
        },
        "tensorflow_v1/1_Introduction/basic_eager_api.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/1_Introduction/basic_eager_api.py\", line 23, in <module>\n",
                "    import tensorflow.contrib.eager as tfe\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/__init__.py\", line 40, in <module>\n",
                "    from tensorflow.contrib import distribute\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/__init__.py\", line 33, in <module>\n",
                "    from tensorflow.contrib.distribute.python.tpu_strategy import TPUStrategy\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/tpu_strategy.py\", line 27, in <module>\n",
                "    from tensorflow.contrib.tpu.python.ops import tpu_ops\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/__init__.py\", line 73, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu.keras_support import tpu_model as keras_to_tpu_model\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py\", line 62, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu import tpu\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu.py\", line 24, in <module>\n",
                "    from tensorflow.contrib.compiler import xla\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/compiler/xla.py\", line 28, in <module>\n",
                "    from tensorflow.python.estimator import model_fn as model_fn_lib\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/python/estimator/__init__.py\", line 26, in <module>\n",
                "    from tensorflow_estimator.python import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1 import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1.estimator import experimental\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py\", line 31, in <module>\n",
                "    from tensorflow_estimator.python.estimator import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py\", line 33, in <module>\n",
                "    from tensorflow.python.eager import monitoring\n",
                "ImportError: cannot import name monitoring\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 1.9
        },
        "tensorflow_v1/1_Introduction/basic_operations.py": {
            "error": [
                "2021-01-04 12:50:11.478748: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA\n",
                "2021-01-04 12:50:11.482682: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 1999965000 Hz\n",
                "2021-01-04 12:50:11.483048: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55e0bca04b50 executing computations on platform Host. Devices:\n",
                "2021-01-04 12:50:11.483077: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>\n"
            ],
            "output": [
                "a=2, b=3\n",
                "Addition with constants: 5\n",
                "Multiplication with constants: 6\n",
                "Addition with variables: 5\n",
                "Multiplication with variables: 6\n",
                "[[12.]]\n"
            ],
            "retval": 0,
            "seconds": 1.57
        },
        "tensorflow_v1/1_Introduction/helloworld.py": {
            "error": [
                "2021-01-04 12:50:13.226215: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA\n",
                "2021-01-04 12:50:13.229941: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 1999965000 Hz\n",
                "2021-01-04 12:50:13.230290: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x5643a5287180 executing computations on platform Host. Devices:\n",
                "2021-01-04 12:50:13.230317: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>\n"
            ],
            "output": [
                "Hello, TensorFlow!\n"
            ],
            "retval": 0,
            "seconds": 1.66
        },
        "tensorflow_v1/4_Utils/tensorboard_advanced.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/4_Utils/tensorboard_advanced.py\", line 20, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/__init__.py\", line 21, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/input_data.py\", line 30, in <module>\n",
                "    from tensorflow.contrib.learn.python.learn.datasets.mnist import read_data_sets\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/__init__.py\", line 40, in <module>\n",
                "    from tensorflow.contrib import distribute\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/__init__.py\", line 33, in <module>\n",
                "    from tensorflow.contrib.distribute.python.tpu_strategy import TPUStrategy\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/tpu_strategy.py\", line 27, in <module>\n",
                "    from tensorflow.contrib.tpu.python.ops import tpu_ops\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/__init__.py\", line 73, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu.keras_support import tpu_model as keras_to_tpu_model\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py\", line 62, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu import tpu\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu.py\", line 24, in <module>\n",
                "    from tensorflow.contrib.compiler import xla\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/compiler/xla.py\", line 28, in <module>\n",
                "    from tensorflow.python.estimator import model_fn as model_fn_lib\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/python/estimator/__init__.py\", line 26, in <module>\n",
                "    from tensorflow_estimator.python import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1 import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1.estimator import experimental\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py\", line 31, in <module>\n",
                "    from tensorflow_estimator.python.estimator import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py\", line 33, in <module>\n",
                "    from tensorflow.python.eager import monitoring\n",
                "ImportError: cannot import name monitoring\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 1.82
        },
        "tensorflow_v1/4_Utils/tensorboard_basic.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/4_Utils/tensorboard_basic.py\", line 20, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/__init__.py\", line 21, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/input_data.py\", line 30, in <module>\n",
                "    from tensorflow.contrib.learn.python.learn.datasets.mnist import read_data_sets\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/__init__.py\", line 40, in <module>\n",
                "    from tensorflow.contrib import distribute\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/__init__.py\", line 33, in <module>\n",
                "    from tensorflow.contrib.distribute.python.tpu_strategy import TPUStrategy\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/tpu_strategy.py\", line 27, in <module>\n",
                "    from tensorflow.contrib.tpu.python.ops import tpu_ops\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/__init__.py\", line 73, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu.keras_support import tpu_model as keras_to_tpu_model\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py\", line 62, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu import tpu\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu.py\", line 24, in <module>\n",
                "    from tensorflow.contrib.compiler import xla\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/compiler/xla.py\", line 28, in <module>\n",
                "    from tensorflow.python.estimator import model_fn as model_fn_lib\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/python/estimator/__init__.py\", line 26, in <module>\n",
                "    from tensorflow_estimator.python import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1 import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1.estimator import experimental\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py\", line 31, in <module>\n",
                "    from tensorflow_estimator.python.estimator import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py\", line 33, in <module>\n",
                "    from tensorflow.python.eager import monitoring\n",
                "ImportError: cannot import name monitoring\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 1.93
        },
        "tensorflow_v1/5_DataManagement/build_an_image_dataset.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/5_DataManagement/build_an_image_dataset.py\", line 133, in <module>\n",
                "    X, Y = read_images(DATASET_PATH, MODE, batch_size)\n",
                "  File \"tensorflow_v1/5_DataManagement/build_an_image_dataset.py\", line 76, in read_images\n",
                "    classes = sorted(os.walk(dataset_path).__next__()[1])\n",
                "AttributeError: 'generator' object has no attribute '__next__'\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 1.52
        },
        "tensorflow_v1/5_DataManagement/tensorflow_dataset_api.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/5_DataManagement/tensorflow_dataset_api.py\", line 20, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/__init__.py\", line 21, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/input_data.py\", line 30, in <module>\n",
                "    from tensorflow.contrib.learn.python.learn.datasets.mnist import read_data_sets\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/__init__.py\", line 40, in <module>\n",
                "    from tensorflow.contrib import distribute\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/__init__.py\", line 33, in <module>\n",
                "    from tensorflow.contrib.distribute.python.tpu_strategy import TPUStrategy\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/tpu_strategy.py\", line 27, in <module>\n",
                "    from tensorflow.contrib.tpu.python.ops import tpu_ops\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/__init__.py\", line 73, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu.keras_support import tpu_model as keras_to_tpu_model\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py\", line 62, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu import tpu\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu.py\", line 24, in <module>\n",
                "    from tensorflow.contrib.compiler import xla\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/compiler/xla.py\", line 28, in <module>\n",
                "    from tensorflow.python.estimator import model_fn as model_fn_lib\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/python/estimator/__init__.py\", line 26, in <module>\n",
                "    from tensorflow_estimator.python import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1 import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1.estimator import experimental\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py\", line 31, in <module>\n",
                "    from tensorflow_estimator.python.estimator import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py\", line 33, in <module>\n",
                "    from tensorflow.python.eager import monitoring\n",
                "ImportError: cannot import name monitoring\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 1.97
        },
        "tensorflow_v1/2_BasicModels/random_forest.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/2_BasicModels/random_forest.py\", line 14, in <module>\n",
                "    from tensorflow.contrib.tensor_forest.python import tensor_forest\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/__init__.py\", line 40, in <module>\n",
                "    from tensorflow.contrib import distribute\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/__init__.py\", line 33, in <module>\n",
                "    from tensorflow.contrib.distribute.python.tpu_strategy import TPUStrategy\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/tpu_strategy.py\", line 27, in <module>\n",
                "    from tensorflow.contrib.tpu.python.ops import tpu_ops\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/__init__.py\", line 73, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu.keras_support import tpu_model as keras_to_tpu_model\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py\", line 62, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu import tpu\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu.py\", line 24, in <module>\n",
                "    from tensorflow.contrib.compiler import xla\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/compiler/xla.py\", line 28, in <module>\n",
                "    from tensorflow.python.estimator import model_fn as model_fn_lib\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/python/estimator/__init__.py\", line 26, in <module>\n",
                "    from tensorflow_estimator.python import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1 import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1.estimator import experimental\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py\", line 31, in <module>\n",
                "    from tensorflow_estimator.python.estimator import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py\", line 33, in <module>\n",
                "    from tensorflow.python.eager import monitoring\n",
                "ImportError: cannot import name monitoring\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 1.89
        },
        "tensorflow_v1/2_BasicModels/gradient_boosted_decision_tree.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/2_BasicModels/gradient_boosted_decision_tree.py\", line 17, in <module>\n",
                "    from tensorflow.contrib.boosted_trees.estimator_batch.estimator import (\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/__init__.py\", line 40, in <module>\n",
                "    from tensorflow.contrib import distribute\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/__init__.py\", line 33, in <module>\n",
                "    from tensorflow.contrib.distribute.python.tpu_strategy import TPUStrategy\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/tpu_strategy.py\", line 27, in <module>\n",
                "    from tensorflow.contrib.tpu.python.ops import tpu_ops\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/__init__.py\", line 73, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu.keras_support import tpu_model as keras_to_tpu_model\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py\", line 62, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu import tpu\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu.py\", line 24, in <module>\n",
                "    from tensorflow.contrib.compiler import xla\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/compiler/xla.py\", line 28, in <module>\n",
                "    from tensorflow.python.estimator import model_fn as model_fn_lib\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/python/estimator/__init__.py\", line 26, in <module>\n",
                "    from tensorflow_estimator.python import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1 import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1.estimator import experimental\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py\", line 31, in <module>\n",
                "    from tensorflow_estimator.python.estimator import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py\", line 33, in <module>\n",
                "    from tensorflow.python.eager import monitoring\n",
                "ImportError: cannot import name monitoring\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 1.81
        },
        "tensorflow_v1/2_BasicModels/logistic_regression.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/2_BasicModels/logistic_regression.py\", line 21, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/__init__.py\", line 21, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/input_data.py\", line 30, in <module>\n",
                "    from tensorflow.contrib.learn.python.learn.datasets.mnist import read_data_sets\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/__init__.py\", line 40, in <module>\n",
                "    from tensorflow.contrib import distribute\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/__init__.py\", line 33, in <module>\n",
                "    from tensorflow.contrib.distribute.python.tpu_strategy import TPUStrategy\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/tpu_strategy.py\", line 27, in <module>\n",
                "    from tensorflow.contrib.tpu.python.ops import tpu_ops\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/__init__.py\", line 73, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu.keras_support import tpu_model as keras_to_tpu_model\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py\", line 62, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu import tpu\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu.py\", line 24, in <module>\n",
                "    from tensorflow.contrib.compiler import xla\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/compiler/xla.py\", line 28, in <module>\n",
                "    from tensorflow.python.estimator import model_fn as model_fn_lib\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/python/estimator/__init__.py\", line 26, in <module>\n",
                "    from tensorflow_estimator.python import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1 import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1.estimator import experimental\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py\", line 31, in <module>\n",
                "    from tensorflow_estimator.python.estimator import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py\", line 33, in <module>\n",
                "    from tensorflow.python.eager import monitoring\n",
                "ImportError: cannot import name monitoring\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 1.81
        },
        "tensorflow_v1/2_BasicModels/word2vec.py": {
            "error": [
                "WARNING:tensorflow:From /usr/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.\n",
                "Instructions for updating:\n",
                "Colocations handled automatically by placer.\n",
                "WARNING:tensorflow:From /usr/local/lib/python2.7/site-packages/tensorflow/python/ops/array_grad.py:425: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.\n",
                "Instructions for updating:\n",
                "Use tf.cast instead.\n",
                "2021-01-04 12:51:27.654670: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA\n",
                "2021-01-04 12:51:27.677643: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 1999965000 Hz\n",
                "2021-01-04 12:51:27.678034: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55c4b03fc280 executing computations on platform Host. Devices:\n",
                "2021-01-04 12:51:27.678065: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>\n"
            ],
            "output": [
                "Downloading the dataset... (It may take some time)\n",
                "Done!\n",
                "Words count: 17005207\n",
                "Unique words: 253854\n",
                "Vocabulary size: 47135\n",
                "Most common words: [('UNK', 444176), ('the', 1061396), ('of', 593677), ('and', 416629), ('one', 411764), ('in', 372201), ('a', 325873), ('to', 316376), ('zero', 264975), ('nine', 250430)]\n",
                "Step 1, Average Loss= 541.8270\n",
                "Evaluation...\n",
                "\"five\" nearest neighbors: philanthropy, closet, appreciate, dst, brainchild, nolo, thz, courtois,\n",
                "\"of\" nearest neighbors: sieve, ignoring, colloquium, ghostbusters, inquire, parallelism, unending, mathcal,\n",
                "\"going\" nearest neighbors: entente, attentions, girardeau, integrable, cake, basso, switches, ephraim,\n",
                "\"hardware\" nearest neighbors: fronting, possibility, du, nutrient, huckleberry, cantonese, subregion, ostwald,\n",
                "\"american\" nearest neighbors: censured, entrepreneur, benito, flockhart, rejoiced, employment, shaun, spiritual,\n",
                "\"britain\" nearest neighbors: breached, gl, hosts, molotov, car, solanaceae, accounting, raping,\n",
                "Step 2, Average Loss= 539.8088\n",
                "Evaluation...\n",
                "\"five\" nearest neighbors: philanthropy, closet, appreciate, dst, brainchild, nolo, thz, courtois,\n",
                "\"of\" nearest neighbors: sieve, colloquium, ignoring, inquire, ghostbusters, parallelism, unending, mathcal,\n",
                "\"going\" nearest neighbors: entente, attentions, girardeau, integrable, cake, basso, switches, ephraim,\n",
                "\"hardware\" nearest neighbors: fronting, possibility, du, nutrient, huckleberry, cantonese, subregion, ostwald,\n",
                "\"american\" nearest neighbors: censured, entrepreneur, benito, flockhart, rejoiced, employment, shaun, spiritual,\n",
                "\"britain\" nearest neighbors: breached, gl, hosts, molotov, car, solanaceae, accounting, raping,\n",
                "Step 3, Average Loss= 530.0865\n",
                "Evaluation...\n",
                "\"five\" nearest neighbors: philanthropy, closet, appreciate, dst, brainchild, nolo, thz, courtois,\n",
                "\"of\" nearest neighbors: sieve, ignoring, colloquium, inquire, ghostbusters, parallelism, mathcal, unending,\n",
                "\"going\" nearest neighbors: entente, attentions, girardeau, integrable, cake, basso, switches, ephraim,\n",
                "\"hardware\" nearest neighbors: fronting, possibility, du, nutrient, huckleberry, cantonese, subregion, ostwald,\n",
                "\"american\" nearest neighbors: censured, entrepreneur, benito, flockhart, rejoiced, employment, shaun, spiritual,\n",
                "\"britain\" nearest neighbors: breached, gl, hosts, molotov, car, solanaceae, accounting, raping,\n",
                "Step 4, Average Loss= 518.4069\n",
                "Evaluation...\n",
                "\"five\" nearest neighbors: philanthropy, closet, appreciate, dst, brainchild, nolo, thz, courtois,\n",
                "\"of\" nearest neighbors: sieve, ignoring, colloquium, inquire, ghostbusters, parallelism, mathcal, unending,\n",
                "\"going\" nearest neighbors: entente, attentions, girardeau, integrable, cake, basso, switches, ephraim,\n",
                "\"hardware\" nearest neighbors: fronting, possibility, du, nutrient, huckleberry, cantonese, subregion, ostwald,\n",
                "\"american\" nearest neighbors: censured, entrepreneur, benito, flockhart, rejoiced, employment, shaun, spiritual,\n",
                "\"britain\" nearest neighbors: breached, gl, hosts, molotov, car, solanaceae, accounting, raping,\n",
                "Step 5, Average Loss= 514.0163\n",
                "Evaluation...\n",
                "\"five\" nearest neighbors: philanthropy, closet, appreciate, dst, brainchild, nolo, thz, courtois,\n",
                "\"of\" nearest neighbors: sieve, colloquium, ignoring, inquire, parallelism, ghostbusters, mathcal, fails,\n",
                "\"going\" nearest neighbors: entente, attentions, girardeau, integrable, cake, basso, switches, ephraim,\n",
                "\"hardware\" nearest neighbors: fronting, possibility, du, nutrient, huckleberry, cantonese, subregion, ostwald,\n",
                "\"american\" nearest neighbors: censured, entrepreneur, benito, flockhart, rejoiced, employment, shaun, spiritual,\n",
                "\"britain\" nearest neighbors: breached, gl, hosts, molotov, car, solanaceae, accounting, raping,\n",
                "Step 6, Average Loss= 516.4792\n",
                "Evaluation...\n",
                "\"five\" nearest neighbors: philanthropy, closet, appreciate, dst, brainchild, nolo, thz, courtois,\n",
                "\"of\" nearest neighbors: sieve, ignoring, colloquium, inquire, parallelism, ghostbusters, fails, discontinuation,\n",
                "\"going\" nearest neighbors: entente, attentions, girardeau, integrable, cake, basso, switches, ephraim,\n",
                "\"hardware\" nearest neighbors: fronting, possibility, du, nutrient, huckleberry, cantonese, subregion, ostwald,\n",
                "\"american\" nearest neighbors: censured, entrepreneur, benito, flockhart, rejoiced, employment, shaun, spiritual,\n",
                "\"britain\" nearest neighbors: breached, gl, hosts, molotov, car, solanaceae, accounting, raping,\n",
                "Step 7, Average Loss= 501.3408\n",
                "Evaluation...\n",
                "\"five\" nearest neighbors: philanthropy, closet, appreciate, dst, brainchild, nolo, thz, courtois,\n",
                "\"of\" nearest neighbors: sieve, ignoring, colloquium, inquire, parallelism, ghostbusters, fails, discontinuation,\n",
                "\"going\" nearest neighbors: entente, attentions, girardeau, integrable, cake, basso, switches, ephraim,\n",
                "\"hardware\" nearest neighbors: fronting, possibility, du, nutrient, huckleberry, cantonese, subregion, ostwald,\n",
                "\"american\" nearest neighbors: censured, entrepreneur, benito, flockhart, rejoiced, employment, shaun, spiritual,\n",
                "\"britain\" nearest neighbors: breached, gl, hosts, molotov, car, solanaceae, accounting, raping,\n",
                "Step 8, Average Loss= 508.7161\n",
                "Evaluation...\n",
                "\"five\" nearest neighbors: philanthropy, closet, appreciate, dst, brainchild, nolo, thz, courtois,\n",
                "\"of\" nearest neighbors: sieve, ignoring, colloquium, inquire, parallelism, ghostbusters, fails, mathcal,\n",
                "\"going\" nearest neighbors: entente, attentions, girardeau, integrable, cake, basso, switches, ephraim,\n",
                "\"hardware\" nearest neighbors: fronting, possibility, du, nutrient, huckleberry, cantonese, subregion, ostwald,\n",
                "\"american\" nearest neighbors: censured, entrepreneur, benito, employment, rejoiced, flockhart, shaun, spiritual,\n",
                "\"britain\" nearest neighbors: breached, gl, hosts, molotov, car, solanaceae, accounting, raping,\n",
                "Step 9, Average Loss= 489.2355\n",
                "Evaluation...\n",
                "\"five\" nearest neighbors: philanthropy, closet, appreciate, dst, brainchild, nolo, thz, courtois,\n",
                "\"of\" nearest neighbors: sieve, ignoring, colloquium, inquire, parallelism, ghostbusters, fails, discontinuation,\n",
                "\"going\" nearest neighbors: entente, attentions, girardeau, integrable, cake, basso, switches, ephraim,\n",
                "\"hardware\" nearest neighbors: fronting, possibility, du, nutrient, huckleberry, cantonese, subregion, ostwald,\n",
                "\"american\" nearest neighbors: censured, entrepreneur, benito, employment, rejoiced, flockhart, shaun, spiritual,\n",
                "\"britain\" nearest neighbors: breached, gl, hosts, molotov, car, solanaceae, accounting, raping,\n",
                "Step 10, Average Loss= 534.6769\n",
                "Evaluation...\n",
                "\"five\" nearest neighbors: philanthropy, closet, appreciate, dst, brainchild, nolo, thz, courtois,\n",
                "\"of\" nearest neighbors: sieve, ignoring, colloquium, parallelism, inquire, ghostbusters, fails, discontinuation,\n",
                "\"going\" nearest neighbors: entente, attentions, girardeau, integrable, cake, basso, switches, ephraim,\n",
                "\"hardware\" nearest neighbors: fronting, possibility, du, nutrient, huckleberry, cantonese, subregion, ostwald,\n",
                "\"american\" nearest neighbors: censured, entrepreneur, benito, employment, rejoiced, flockhart, shaun, spiritual,\n",
                "\"britain\" nearest neighbors: breached, gl, hosts, molotov, car, solanaceae, accounting, raping,\n"
            ],
            "retval": 0,
            "seconds": 63.47
        },
        "tensorflow_v1/2_BasicModels/linear_regression.py": {
            "error": [
                "WARNING:tensorflow:From /usr/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.\n",
                "Instructions for updating:\n",
                "Colocations handled automatically by placer.\n",
                "WARNING:tensorflow:From /usr/local/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.\n",
                "Instructions for updating:\n",
                "Use tf.cast instead.\n",
                "2021-01-04 12:51:31.111507: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA\n",
                "2021-01-04 12:51:31.117122: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 1999965000 Hz\n",
                "2021-01-04 12:51:31.117503: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x5626fbf65290 executing computations on platform Host. Devices:\n",
                "2021-01-04 12:51:31.117528: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>\n"
            ],
            "output": [
                "Epoch: 0050 cost= 0.213137463 W= 0.4558863 b= -0.6825888\n",
                "Epoch: 0100 cost= 0.197407037 W= 0.443617 b= -0.5943239\n",
                "Optimization Finished!\n",
                "Training cost= 0.19740704 W= 0.443617 b= -0.5943239 \n",
                "\n"
            ],
            "retval": 0,
            "seconds": 2.41
        },
        "tensorflow_v1/2_BasicModels/logistic_regression_eager_api.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/2_BasicModels/logistic_regression_eager_api.py\", line 20, in <module>\n",
                "    tf.enable_eager_execution()\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py\", line 5461, in enable_eager_execution\n",
                "    server_def=None)\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py\", line 5516, in enable_eager_execution_internal\n",
                "    \"tf.enable_eager_execution must be called at program startup.\")\n",
                "ValueError: tf.enable_eager_execution must be called at program startup.\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 1.52
        },
        "tensorflow_v1/2_BasicModels/nearest_neighbor.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/2_BasicModels/nearest_neighbor.py\", line 23, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/__init__.py\", line 21, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/input_data.py\", line 30, in <module>\n",
                "    from tensorflow.contrib.learn.python.learn.datasets.mnist import read_data_sets\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/__init__.py\", line 40, in <module>\n",
                "    from tensorflow.contrib import distribute\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/__init__.py\", line 33, in <module>\n",
                "    from tensorflow.contrib.distribute.python.tpu_strategy import TPUStrategy\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/tpu_strategy.py\", line 27, in <module>\n",
                "    from tensorflow.contrib.tpu.python.ops import tpu_ops\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/__init__.py\", line 73, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu.keras_support import tpu_model as keras_to_tpu_model\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py\", line 62, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu import tpu\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu.py\", line 24, in <module>\n",
                "    from tensorflow.contrib.compiler import xla\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/compiler/xla.py\", line 28, in <module>\n",
                "    from tensorflow.python.estimator import model_fn as model_fn_lib\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/python/estimator/__init__.py\", line 26, in <module>\n",
                "    from tensorflow_estimator.python import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1 import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1.estimator import experimental\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py\", line 31, in <module>\n",
                "    from tensorflow_estimator.python.estimator import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py\", line 33, in <module>\n",
                "    from tensorflow.python.eager import monitoring\n",
                "ImportError: cannot import name monitoring\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 1.87
        },
        "tensorflow_v1/2_BasicModels/linear_regression_eager_api.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/2_BasicModels/linear_regression_eager_api.py\", line 21, in <module>\n",
                "    tf.enable_eager_execution()\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py\", line 5461, in enable_eager_execution\n",
                "    server_def=None)\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py\", line 5516, in enable_eager_execution_internal\n",
                "    \"tf.enable_eager_execution must be called at program startup.\")\n",
                "ValueError: tf.enable_eager_execution must be called at program startup.\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 1.58
        },
        "tensorflow_v1/2_BasicModels/kmeans.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/2_BasicModels/kmeans.py\", line 17, in <module>\n",
                "    from tensorflow.contrib.factorization import KMeans\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/__init__.py\", line 40, in <module>\n",
                "    from tensorflow.contrib import distribute\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/__init__.py\", line 33, in <module>\n",
                "    from tensorflow.contrib.distribute.python.tpu_strategy import TPUStrategy\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/tpu_strategy.py\", line 27, in <module>\n",
                "    from tensorflow.contrib.tpu.python.ops import tpu_ops\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/__init__.py\", line 73, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu.keras_support import tpu_model as keras_to_tpu_model\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py\", line 62, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu import tpu\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu.py\", line 24, in <module>\n",
                "    from tensorflow.contrib.compiler import xla\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/compiler/xla.py\", line 28, in <module>\n",
                "    from tensorflow.python.estimator import model_fn as model_fn_lib\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/python/estimator/__init__.py\", line 26, in <module>\n",
                "    from tensorflow_estimator.python import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1 import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1.estimator import experimental\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py\", line 31, in <module>\n",
                "    from tensorflow_estimator.python.estimator import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py\", line 33, in <module>\n",
                "    from tensorflow.python.eager import monitoring\n",
                "ImportError: cannot import name monitoring\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 1.89
        },
        "tensorflow_v1/6_MultiGPU/multigpu_basics.py": {
            "error": [
                "2021-01-04 12:51:40.488491: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA\n",
                "2021-01-04 12:51:40.497722: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 1999965000 Hz\n",
                "2021-01-04 12:51:40.498051: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x5574f32d0780 executing computations on platform Host. Devices:\n",
                "2021-01-04 12:51:40.498077: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>\n",
                "2021-01-04 12:51:40.498397: I tensorflow/core/common_runtime/direct_session.cc:317] Device mapping:\n",
                "/job:localhost/replica:0/task:0/device:XLA_CPU:0 -> device: XLA_CPU device\n",
                "\n",
                "2021-01-04 12:51:40.500596: I tensorflow/core/common_runtime/placer.cc:1059] MatMul: (MatMul)/job:localhost/replica:0/task:0/device:CPU:0\n",
                "2021-01-04 12:51:40.500633: I tensorflow/core/common_runtime/placer.cc:1059] MatMul_1: (MatMul)/job:localhost/replica:0/task:0/device:CPU:0\n",
                "2021-01-04 12:51:40.500645: I tensorflow/core/common_runtime/placer.cc:1059] AddN: (AddN)/job:localhost/replica:0/task:0/device:CPU:0\n",
                "2021-01-04 12:51:40.500657: I tensorflow/core/common_runtime/placer.cc:1059] Placeholder: (Placeholder)/job:localhost/replica:0/task:0/device:CPU:0\n",
                "2021-01-04 12:51:40.500668: I tensorflow/core/common_runtime/placer.cc:1059] Placeholder_1: (Placeholder)/job:localhost/replica:0/task:0/device:CPU:0\n",
                "2021-01-04 12:51:40.544185: I tensorflow/core/common_runtime/direct_session.cc:317] Device mapping:\n",
                "/job:localhost/replica:0/task:0/device:XLA_CPU:0 -> device: XLA_CPU device\n",
                "\n",
                "2021-01-04 12:51:40.545949: I tensorflow/core/common_runtime/placer.cc:1059] MatMul: (MatMul)/job:localhost/replica:0/task:0/device:CPU:0\n",
                "2021-01-04 12:51:40.545984: I tensorflow/core/common_runtime/placer.cc:1059] MatMul_1: (MatMul)/job:localhost/replica:0/task:0/device:CPU:0\n",
                "2021-01-04 12:51:40.545999: I tensorflow/core/common_runtime/placer.cc:1059] AddN: (AddN)/job:localhost/replica:0/task:0/device:CPU:0\n",
                "2021-01-04 12:51:40.546011: I tensorflow/core/common_runtime/placer.cc:1059] MatMul_2: (MatMul)/job:localhost/replica:0/task:0/device:CPU:0\n",
                "2021-01-04 12:51:40.546024: I tensorflow/core/common_runtime/placer.cc:1059] MatMul_3: (MatMul)/job:localhost/replica:0/task:0/device:CPU:0\n",
                "2021-01-04 12:51:40.546039: I tensorflow/core/common_runtime/placer.cc:1059] AddN_1: (AddN)/job:localhost/replica:0/task:0/device:CPU:0\n",
                "2021-01-04 12:51:40.546050: I tensorflow/core/common_runtime/placer.cc:1059] Placeholder: (Placeholder)/job:localhost/replica:0/task:0/device:CPU:0\n",
                "2021-01-04 12:51:40.546060: I tensorflow/core/common_runtime/placer.cc:1059] Placeholder_1: (Placeholder)/job:localhost/replica:0/task:0/device:CPU:0\n",
                "2021-01-04 12:51:40.546070: I tensorflow/core/common_runtime/placer.cc:1059] Placeholder_2: (Placeholder)/job:localhost/replica:0/task:0/device:CPU:0\n",
                "2021-01-04 12:51:40.546083: I tensorflow/core/common_runtime/placer.cc:1059] Placeholder_3: (Placeholder)/job:localhost/replica:0/task:0/device:CPU:0\n"
            ],
            "output": [
                "Device mapping:\n",
                "/job:localhost/replica:0/task:0/device:XLA_CPU:0 -> device: XLA_CPU device\n",
                "MatMul: (MatMul): /job:localhost/replica:0/task:0/device:CPU:0\n",
                "MatMul_1: (MatMul): /job:localhost/replica:0/task:0/device:CPU:0\n",
                "AddN: (AddN): /job:localhost/replica:0/task:0/device:CPU:0\n",
                "Placeholder: (Placeholder): /job:localhost/replica:0/task:0/device:CPU:0\n",
                "Placeholder_1: (Placeholder): /job:localhost/replica:0/task:0/device:CPU:0\n",
                "Device mapping:\n",
                "/job:localhost/replica:0/task:0/device:XLA_CPU:0 -> device: XLA_CPU device\n",
                "MatMul: (MatMul): /job:localhost/replica:0/task:0/device:CPU:0\n",
                "MatMul_1: (MatMul): /job:localhost/replica:0/task:0/device:CPU:0\n",
                "AddN: (AddN): /job:localhost/replica:0/task:0/device:CPU:0\n",
                "MatMul_2: (MatMul): /job:localhost/replica:0/task:0/device:CPU:0\n",
                "MatMul_3: (MatMul): /job:localhost/replica:0/task:0/device:CPU:0\n",
                "AddN_1: (AddN): /job:localhost/replica:0/task:0/device:CPU:0\n",
                "Placeholder: (Placeholder): /job:localhost/replica:0/task:0/device:CPU:0\n",
                "Placeholder_1: (Placeholder): /job:localhost/replica:0/task:0/device:CPU:0\n",
                "Placeholder_2: (Placeholder): /job:localhost/replica:0/task:0/device:CPU:0\n",
                "Placeholder_3: (Placeholder): /job:localhost/replica:0/task:0/device:CPU:0\n",
                "Single CPU computation time: 0:00:00.051472\n",
                "Multi CPU computation time: 0:00:00.042854\n"
            ],
            "retval": 0,
            "seconds": 1.89
        },
        "tensorflow_v1/6_MultiGPU/multigpu_cnn.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/6_MultiGPU/multigpu_cnn.py\", line 28, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/__init__.py\", line 21, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/input_data.py\", line 30, in <module>\n",
                "    from tensorflow.contrib.learn.python.learn.datasets.mnist import read_data_sets\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/__init__.py\", line 40, in <module>\n",
                "    from tensorflow.contrib import distribute\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/__init__.py\", line 33, in <module>\n",
                "    from tensorflow.contrib.distribute.python.tpu_strategy import TPUStrategy\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/tpu_strategy.py\", line 27, in <module>\n",
                "    from tensorflow.contrib.tpu.python.ops import tpu_ops\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/__init__.py\", line 73, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu.keras_support import tpu_model as keras_to_tpu_model\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py\", line 62, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu import tpu\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu.py\", line 24, in <module>\n",
                "    from tensorflow.contrib.compiler import xla\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/compiler/xla.py\", line 28, in <module>\n",
                "    from tensorflow.python.estimator import model_fn as model_fn_lib\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/python/estimator/__init__.py\", line 26, in <module>\n",
                "    from tensorflow_estimator.python import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1 import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1.estimator import experimental\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py\", line 31, in <module>\n",
                "    from tensorflow_estimator.python.estimator import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py\", line 33, in <module>\n",
                "    from tensorflow.python.eager import monitoring\n",
                "ImportError: cannot import name monitoring\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 1.81
        },
        "tensorflow_v1/3_NeuralNetworks/variational_autoencoder.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/3_NeuralNetworks/variational_autoencoder.py\", line 35, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/__init__.py\", line 21, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/input_data.py\", line 30, in <module>\n",
                "    from tensorflow.contrib.learn.python.learn.datasets.mnist import read_data_sets\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/__init__.py\", line 40, in <module>\n",
                "    from tensorflow.contrib import distribute\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/__init__.py\", line 33, in <module>\n",
                "    from tensorflow.contrib.distribute.python.tpu_strategy import TPUStrategy\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/tpu_strategy.py\", line 27, in <module>\n",
                "    from tensorflow.contrib.tpu.python.ops import tpu_ops\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/__init__.py\", line 73, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu.keras_support import tpu_model as keras_to_tpu_model\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py\", line 62, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu import tpu\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu.py\", line 24, in <module>\n",
                "    from tensorflow.contrib.compiler import xla\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/compiler/xla.py\", line 28, in <module>\n",
                "    from tensorflow.python.estimator import model_fn as model_fn_lib\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/python/estimator/__init__.py\", line 26, in <module>\n",
                "    from tensorflow_estimator.python import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1 import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1.estimator import experimental\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py\", line 31, in <module>\n",
                "    from tensorflow_estimator.python.estimator import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py\", line 33, in <module>\n",
                "    from tensorflow.python.eager import monitoring\n",
                "ImportError: cannot import name monitoring\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 1.7
        },
        "tensorflow_v1/3_NeuralNetworks/neural_network_eager_api.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/3_NeuralNetworks/neural_network_eager_api.py\", line 26, in <module>\n",
                "    tf.enable_eager_execution()\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py\", line 5461, in enable_eager_execution\n",
                "    server_def=None)\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py\", line 5516, in enable_eager_execution_internal\n",
                "    \"tf.enable_eager_execution must be called at program startup.\")\n",
                "ValueError: tf.enable_eager_execution must be called at program startup.\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 1.72
        },
        "tensorflow_v1/3_NeuralNetworks/neural_network.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/3_NeuralNetworks/neural_network.py\", line 20, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/__init__.py\", line 21, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/input_data.py\", line 30, in <module>\n",
                "    from tensorflow.contrib.learn.python.learn.datasets.mnist import read_data_sets\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/__init__.py\", line 40, in <module>\n",
                "    from tensorflow.contrib import distribute\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/__init__.py\", line 33, in <module>\n",
                "    from tensorflow.contrib.distribute.python.tpu_strategy import TPUStrategy\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/tpu_strategy.py\", line 27, in <module>\n",
                "    from tensorflow.contrib.tpu.python.ops import tpu_ops\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/__init__.py\", line 73, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu.keras_support import tpu_model as keras_to_tpu_model\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py\", line 62, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu import tpu\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu.py\", line 24, in <module>\n",
                "    from tensorflow.contrib.compiler import xla\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/compiler/xla.py\", line 28, in <module>\n",
                "    from tensorflow.python.estimator import model_fn as model_fn_lib\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/python/estimator/__init__.py\", line 26, in <module>\n",
                "    from tensorflow_estimator.python import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1 import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1.estimator import experimental\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py\", line 31, in <module>\n",
                "    from tensorflow_estimator.python.estimator import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py\", line 33, in <module>\n",
                "    from tensorflow.python.eager import monitoring\n",
                "ImportError: cannot import name monitoring\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 1.85
        },
        "tensorflow_v1/3_NeuralNetworks/bidirectional_rnn.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/3_NeuralNetworks/bidirectional_rnn.py\", line 18, in <module>\n",
                "    from tensorflow.contrib import rnn\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/__init__.py\", line 40, in <module>\n",
                "    from tensorflow.contrib import distribute\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/__init__.py\", line 33, in <module>\n",
                "    from tensorflow.contrib.distribute.python.tpu_strategy import TPUStrategy\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/tpu_strategy.py\", line 27, in <module>\n",
                "    from tensorflow.contrib.tpu.python.ops import tpu_ops\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/__init__.py\", line 73, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu.keras_support import tpu_model as keras_to_tpu_model\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py\", line 62, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu import tpu\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu.py\", line 24, in <module>\n",
                "    from tensorflow.contrib.compiler import xla\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/compiler/xla.py\", line 28, in <module>\n",
                "    from tensorflow.python.estimator import model_fn as model_fn_lib\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/python/estimator/__init__.py\", line 26, in <module>\n",
                "    from tensorflow_estimator.python import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1 import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1.estimator import experimental\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py\", line 31, in <module>\n",
                "    from tensorflow_estimator.python.estimator import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py\", line 33, in <module>\n",
                "    from tensorflow.python.eager import monitoring\n",
                "ImportError: cannot import name monitoring\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 1.66
        },
        "tensorflow_v1/3_NeuralNetworks/convolutional_network_raw.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/3_NeuralNetworks/convolutional_network_raw.py\", line 16, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/__init__.py\", line 21, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/input_data.py\", line 30, in <module>\n",
                "    from tensorflow.contrib.learn.python.learn.datasets.mnist import read_data_sets\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/__init__.py\", line 40, in <module>\n",
                "    from tensorflow.contrib import distribute\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/__init__.py\", line 33, in <module>\n",
                "    from tensorflow.contrib.distribute.python.tpu_strategy import TPUStrategy\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/tpu_strategy.py\", line 27, in <module>\n",
                "    from tensorflow.contrib.tpu.python.ops import tpu_ops\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/__init__.py\", line 73, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu.keras_support import tpu_model as keras_to_tpu_model\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py\", line 62, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu import tpu\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu.py\", line 24, in <module>\n",
                "    from tensorflow.contrib.compiler import xla\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/compiler/xla.py\", line 28, in <module>\n",
                "    from tensorflow.python.estimator import model_fn as model_fn_lib\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/python/estimator/__init__.py\", line 26, in <module>\n",
                "    from tensorflow_estimator.python import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1 import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1.estimator import experimental\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py\", line 31, in <module>\n",
                "    from tensorflow_estimator.python.estimator import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py\", line 33, in <module>\n",
                "    from tensorflow.python.eager import monitoring\n",
                "ImportError: cannot import name monitoring\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 1.93
        },
        "tensorflow_v1/3_NeuralNetworks/autoencoder.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/3_NeuralNetworks/autoencoder.py\", line 30, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/__init__.py\", line 21, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/input_data.py\", line 30, in <module>\n",
                "    from tensorflow.contrib.learn.python.learn.datasets.mnist import read_data_sets\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/__init__.py\", line 40, in <module>\n",
                "    from tensorflow.contrib import distribute\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/__init__.py\", line 33, in <module>\n",
                "    from tensorflow.contrib.distribute.python.tpu_strategy import TPUStrategy\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/tpu_strategy.py\", line 27, in <module>\n",
                "    from tensorflow.contrib.tpu.python.ops import tpu_ops\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/__init__.py\", line 73, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu.keras_support import tpu_model as keras_to_tpu_model\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py\", line 62, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu import tpu\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu.py\", line 24, in <module>\n",
                "    from tensorflow.contrib.compiler import xla\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/compiler/xla.py\", line 28, in <module>\n",
                "    from tensorflow.python.estimator import model_fn as model_fn_lib\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/python/estimator/__init__.py\", line 26, in <module>\n",
                "    from tensorflow_estimator.python import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1 import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1.estimator import experimental\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py\", line 31, in <module>\n",
                "    from tensorflow_estimator.python.estimator import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py\", line 33, in <module>\n",
                "    from tensorflow.python.eager import monitoring\n",
                "ImportError: cannot import name monitoring\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 1.82
        },
        "tensorflow_v1/3_NeuralNetworks/gan.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/3_NeuralNetworks/gan.py\", line 35, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/__init__.py\", line 21, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/input_data.py\", line 30, in <module>\n",
                "    from tensorflow.contrib.learn.python.learn.datasets.mnist import read_data_sets\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/__init__.py\", line 40, in <module>\n",
                "    from tensorflow.contrib import distribute\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/__init__.py\", line 33, in <module>\n",
                "    from tensorflow.contrib.distribute.python.tpu_strategy import TPUStrategy\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/tpu_strategy.py\", line 27, in <module>\n",
                "    from tensorflow.contrib.tpu.python.ops import tpu_ops\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/__init__.py\", line 73, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu.keras_support import tpu_model as keras_to_tpu_model\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py\", line 62, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu import tpu\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu.py\", line 24, in <module>\n",
                "    from tensorflow.contrib.compiler import xla\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/compiler/xla.py\", line 28, in <module>\n",
                "    from tensorflow.python.estimator import model_fn as model_fn_lib\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/python/estimator/__init__.py\", line 26, in <module>\n",
                "    from tensorflow_estimator.python import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1 import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1.estimator import experimental\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py\", line 31, in <module>\n",
                "    from tensorflow_estimator.python.estimator import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py\", line 33, in <module>\n",
                "    from tensorflow.python.eager import monitoring\n",
                "ImportError: cannot import name monitoring\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 1.89
        },
        "tensorflow_v1/3_NeuralNetworks/recurrent_network.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/3_NeuralNetworks/recurrent_network.py\", line 17, in <module>\n",
                "    from tensorflow.contrib import rnn\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/__init__.py\", line 40, in <module>\n",
                "    from tensorflow.contrib import distribute\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/__init__.py\", line 33, in <module>\n",
                "    from tensorflow.contrib.distribute.python.tpu_strategy import TPUStrategy\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/tpu_strategy.py\", line 27, in <module>\n",
                "    from tensorflow.contrib.tpu.python.ops import tpu_ops\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/__init__.py\", line 73, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu.keras_support import tpu_model as keras_to_tpu_model\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py\", line 62, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu import tpu\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu.py\", line 24, in <module>\n",
                "    from tensorflow.contrib.compiler import xla\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/compiler/xla.py\", line 28, in <module>\n",
                "    from tensorflow.python.estimator import model_fn as model_fn_lib\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/python/estimator/__init__.py\", line 26, in <module>\n",
                "    from tensorflow_estimator.python import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1 import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1.estimator import experimental\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py\", line 31, in <module>\n",
                "    from tensorflow_estimator.python.estimator import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py\", line 33, in <module>\n",
                "    from tensorflow.python.eager import monitoring\n",
                "ImportError: cannot import name monitoring\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 1.62
        },
        "tensorflow_v1/3_NeuralNetworks/neural_network_raw.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/3_NeuralNetworks/neural_network_raw.py\", line 17, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/__init__.py\", line 21, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/input_data.py\", line 30, in <module>\n",
                "    from tensorflow.contrib.learn.python.learn.datasets.mnist import read_data_sets\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/__init__.py\", line 40, in <module>\n",
                "    from tensorflow.contrib import distribute\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/__init__.py\", line 33, in <module>\n",
                "    from tensorflow.contrib.distribute.python.tpu_strategy import TPUStrategy\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/tpu_strategy.py\", line 27, in <module>\n",
                "    from tensorflow.contrib.tpu.python.ops import tpu_ops\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/__init__.py\", line 73, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu.keras_support import tpu_model as keras_to_tpu_model\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py\", line 62, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu import tpu\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu.py\", line 24, in <module>\n",
                "    from tensorflow.contrib.compiler import xla\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/compiler/xla.py\", line 28, in <module>\n",
                "    from tensorflow.python.estimator import model_fn as model_fn_lib\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/python/estimator/__init__.py\", line 26, in <module>\n",
                "    from tensorflow_estimator.python import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1 import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1.estimator import experimental\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py\", line 31, in <module>\n",
                "    from tensorflow_estimator.python.estimator import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py\", line 33, in <module>\n",
                "    from tensorflow.python.eager import monitoring\n",
                "ImportError: cannot import name monitoring\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 1.95
        },
        "tensorflow_v1/3_NeuralNetworks/multilayer_perceptron.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/3_NeuralNetworks/multilayer_perceptron.py\", line 24, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/__init__.py\", line 21, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/input_data.py\", line 30, in <module>\n",
                "    from tensorflow.contrib.learn.python.learn.datasets.mnist import read_data_sets\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/__init__.py\", line 40, in <module>\n",
                "    from tensorflow.contrib import distribute\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/__init__.py\", line 33, in <module>\n",
                "    from tensorflow.contrib.distribute.python.tpu_strategy import TPUStrategy\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/tpu_strategy.py\", line 27, in <module>\n",
                "    from tensorflow.contrib.tpu.python.ops import tpu_ops\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/__init__.py\", line 73, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu.keras_support import tpu_model as keras_to_tpu_model\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py\", line 62, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu import tpu\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu.py\", line 24, in <module>\n",
                "    from tensorflow.contrib.compiler import xla\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/compiler/xla.py\", line 28, in <module>\n",
                "    from tensorflow.python.estimator import model_fn as model_fn_lib\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/python/estimator/__init__.py\", line 26, in <module>\n",
                "    from tensorflow_estimator.python import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1 import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1.estimator import experimental\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py\", line 31, in <module>\n",
                "    from tensorflow_estimator.python.estimator import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py\", line 33, in <module>\n",
                "    from tensorflow.python.eager import monitoring\n",
                "ImportError: cannot import name monitoring\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 1.95
        },
        "tensorflow_v1/3_NeuralNetworks/convolutional_network.py": {
            "error": [
                "Traceback (most recent call last):\n",
                "  File \"tensorflow_v1/3_NeuralNetworks/convolutional_network.py\", line 16, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/__init__.py\", line 21, in <module>\n",
                "    from tensorflow.examples.tutorials.mnist import input_data\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist/input_data.py\", line 30, in <module>\n",
                "    from tensorflow.contrib.learn.python.learn.datasets.mnist import read_data_sets\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/__init__.py\", line 40, in <module>\n",
                "    from tensorflow.contrib import distribute\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/__init__.py\", line 33, in <module>\n",
                "    from tensorflow.contrib.distribute.python.tpu_strategy import TPUStrategy\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/tpu_strategy.py\", line 27, in <module>\n",
                "    from tensorflow.contrib.tpu.python.ops import tpu_ops\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/__init__.py\", line 73, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu.keras_support import tpu_model as keras_to_tpu_model\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py\", line 62, in <module>\n",
                "    from tensorflow.contrib.tpu.python.tpu import tpu\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu.py\", line 24, in <module>\n",
                "    from tensorflow.contrib.compiler import xla\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/contrib/compiler/xla.py\", line 28, in <module>\n",
                "    from tensorflow.python.estimator import model_fn as model_fn_lib\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow/python/estimator/__init__.py\", line 26, in <module>\n",
                "    from tensorflow_estimator.python import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1 import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator._api.v1.estimator import experimental\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py\", line 10, in <module>\n",
                "    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py\", line 31, in <module>\n",
                "    from tensorflow_estimator.python.estimator import estimator\n",
                "  File \"/usr/local/lib/python2.7/site-packages/tensorflow_estimator/python/estimator/estimator.py\", line 33, in <module>\n",
                "    from tensorflow.python.eager import monitoring\n",
                "ImportError: cannot import name monitoring\n"
            ],
            "output": [],
            "retval": 1,
            "seconds": 1.91
        }
    },
    "requirements.txt": [
        "absl-py==0.11.0\n",
        "appdirs==1.4.3\n",
        "astor==0.8.1\n",
        "backports.weakref==1.0.post1\n",
        "configparser==4.0.2\n",
        "contextlib2==0.6.0.post1\n",
        "distlib==0.3.0\n",
        "enum34==1.1.10\n",
        "filelock==3.0.12\n",
        "funcsigs==1.0.2\n",
        "futures==3.3.0\n",
        "gast==0.4.0\n",
        "grpcio==1.34.0\n",
        "h5py==2.10.0\n",
        "importlib-metadata==1.6.0\n",
        "importlib-resources==1.4.0\n",
        "Keras-Applications==1.0.8\n",
        "Keras-Preprocessing==1.1.2\n",
        "Markdown==3.1.1\n",
        "mock==3.0.5\n",
        "numpy==1.16.6\n",
        "pathlib2==2.3.5\n",
        "protobuf==3.14.0\n",
        "scandir==1.10.0\n",
        "singledispatch==3.4.0.3\n",
        "six==1.14.0\n",
        "tensorboard==1.12.2\n",
        "tensorflow==1.13.0rc0\n",
        "tensorflow-estimator==2.4.0\n",
        "termcolor==1.1.0\n",
        "typing==3.7.4.1\n",
        "virtualenv==20.0.18\n",
        "Werkzeug==1.0.1\n",
        "zipp==1.2.0\n"
    ]
}